---
- name: Configure httpd server and deploy website
  hosts: example_instance
  become: true
  vars:
    project_root: /var/www/html
    ansible_python_interpreter: /usr/bin/python3

  tasks: 
    - name: Install Apache Webserver using dnf
      dnf:
        name: httpd
        state: present

    - name: Download zip file
      get_url:
        url: "https://www.tooplate.com/zip-templates/2136_kool_form_pack.zip"
        dest: "/tmp/2136_kool_form_pack.zip"

    - name: Install Apache Webserver using dnf
      dnf:
        name: unzip
        state: present

    - name: Unzip the downloaded file
      command: unzip "/tmp/2136_kool_form_pack.zip" -d "/var/www/html/"
      args:
        creates: "/var/www/html/2136_kool_form_pack/"

    - name: Enable Apache on system reboot
      service: name=httpd enabled=yes
      notify: restart apache

  handlers:
    - name: restart apache
      service: name=httpd state=restarted

